---
title: "MLaE proposal"
author: "Boyu Chen, Yihuai Chang"
date: "2023-04-11"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Research Interest

-   We wanted to know if WFH workers sleep less, and if so, what factors
-   Under the pandemic, although there are many inconveniences, working from home undoubtedly saves workers' commuting time.
-   And if working from home becomes a common measure, the choice of housing location for workers does not need to be very close to the city center,this helps reduce inequality between regions.
-   The current known disadvantages of working from home are: less face-to-face social time, less exposure to sunlight.
    -   These factors may all contribute to poorer sleep among home workers.

## Data Source

IPUMS Time Use 2015\~2021

## Potential problem

### We have only sleep time data

-   We have no data to measure sleep quality, only sleep time.

### Solutions

-   use repeated cross-sectional data.
-   The changes in the sleep time of the experimental group and the control group were tracked through time-series data.

## Model

Consider the following two model 
$$D_i = f(state_i, ind_i, Occ_i, age_i) + u_i$$ 
$$SleepTime_i = D_i + Married_i + Inc_i + Sex_i + NumChildren_i + \epsilon_i$$

- Where $D_i$ is a binary variable,$D_i=1$ if i works from home, $D_i= 0$ o.w.
